### PR TITLE
Add ES6 module support

### PR DESCRIPTION
**Pull request by tylerbuchea**
closes issue #3

### CODE REVIEW

**Comment by peterpme** [comment]
Hey @tylerbuchea!

Thanks so much for this PR!

Do you know if this is any different than the "module" key we have in package.json that points to twitter.m.js?

**Comment by tylerbuchea** [comment]
I'm not really sure I found this article regarding the "module" field and Rollup I'll have to look into it more. https://github.com/rollup/rollup/wiki/pkg.module

Maybe @dandv can shine some more light on the subject?

**Comment by peterpme** [comment]
Awesome. Do you use es6 modules now? Can you try using twitter-lite as an es6 module with what's published and see what happens? I don't really use them yet.

**Comment by tylerbuchea** [comment]
I do use es6 modules now and twitter-lite works fine if I import it as an es6 module. I just tried it to double check.

I did a diff on twitter.js and twitter.m.js and there is no difference I'm not really sure what the module field is supposed to be doing.

I'm actually having second thoughts on this PR. One thing Microbundle gives us besides bundling is ESNext support, which is nice and looking into the future there will probably always be certain features we want to use that aren't supported right away.

**Comment by peterpme** [comment]
Hey @tylerbuchea,

do you think we should close out this PR then?

Thanks!

**Comment by tylerbuchea** [comment]
Definitely, thanks for checking though 😎

**Pull request closed without merging**
